// lib/pages/investment_scheme_detail_page.dart

import 'package:flutter/material.dart';
import 'package:sakhi/invest/investment_scheme.dart';
import 'package:sakhi/theme/save_theme.dart';
class InvestmentSchemeDetailPage extends StatelessWidget {
  final InvestmentScheme scheme;

  const InvestmentSchemeDetailPage({super.key, required this.scheme});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(scheme.name),
        centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: ListView(
          children: [
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    ListTile(
                      leading: Icon(scheme.icon, color: AppTheme.primaryColor, size: 48),
                      title: Text(
                        scheme.name,
                        style: Theme.of(context).textTheme.headlineSmall?.copyWith(color: AppTheme.primaryColor),
                      ),
                      subtitle: Text(scheme.category, style: Theme.of(context).textTheme.bodyMedium),
                      contentPadding: EdgeInsets.zero,
                    ),
                    const Divider(height: 24),
                    Text(
                      'Overview:',
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      scheme.description,
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(height: 16),
                    _buildInfoRow('Risk Level:', scheme.riskLevel, context),
                    _buildInfoRow('Typical Returns:', scheme.typicalReturns, context, highlight: true),
                    _buildInfoRow('Min. Investment:', scheme.minInvestment, context),
                    _buildInfoRow('Lock-in Period:', scheme.lockInPeriod, context),
                    _buildInfoRow('Tax Benefits:', scheme.taxBenefits, context),
                    const SizedBox(height: 16),
                    Text(
                      'How to Get Started:',
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    const SizedBox(height: 8),
                    Text(
                      scheme.howToStart,
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                    const SizedBox(height: 24),
                    Text(
                      'Expected Growth (Sample Chart):',
                      style: Theme.of(context).textTheme.titleLarge,
                    ),
                    const SizedBox(height: 8),
                    // Placeholder for chart
                    Container(
                      height: 180,
                      decoration: BoxDecoration(
                        color: AppTheme.backgroundColor,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(color: Colors.grey[300]!),
                      ),
                      child: Center(
                        child: Text(
                          'Dynamic chart of returns over time will be here\n(Generated by backend using Matplotlib/Plotly)',
                          style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.grey[600]),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                    const SizedBox(height: 24),
                    Center(
                      child: ElevatedButton.icon(
                        onPressed: () {
                          ScaffoldMessenger.of(context).showSnackBar(
                            SnackBar(
                              content: Text('Simulating Download of Detailed Guide for ${scheme.name}...'),
                              backgroundColor: AppTheme.primaryColor,
                              behavior: SnackBarBehavior.floating,
                              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                              margin: const EdgeInsets.all(10),
                            ),
                          );
                        },
                        icon: const Icon(Icons.picture_as_pdf_rounded),
                        label: const Text('Download Full Guide'),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildInfoRow(String label, String value, BuildContext context, {bool highlight = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              fontWeight: highlight ? FontWeight.bold : FontWeight.normal,
              color: highlight ? AppTheme.primaryColor : AppTheme.textColor.withOpacity(0.8),
            ),
          ),
          Text(
            value,
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
              fontWeight: highlight ? FontWeight.bold : FontWeight.normal,
              color: highlight ? AppTheme.primaryColor : AppTheme.textColor,
            ),
          ),
        ],
      ),
    );
  }
}
